from __future__ import annotations

import hashlib
import json
import re
import subprocess
import sys
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = json.loads((ROOT / 'data/lessons/week1.json').read_text(encoding='utf-8'))


class ContentTests(unittest.TestCase):
    def test_version_and_id_present(self):
        self.assertRegex(DATA['version'], r'^\d+\.\d+\.\d+$')
        self.assertRegex(DATA['id'], r'^[a-z0-9-]+$')

    def test_vocabulary_ids_unique(self):
        ids = [item['id'] for item in DATA['vocabulary']]
        self.assertEqual(len(ids), len(set(ids)))

    def test_quiz_answers_are_in_range(self):
        for item in DATA['quiz']:
            self.assertGreaterEqual(item['answer'], 0)
            self.assertLess(item['answer'], len(item['choices']))

    def test_required_family_terms_exist(self):
        ids = {item['id'] for item in DATA['vocabulary']}
        self.assertTrue({'mother','father','older-brother','older-sister','youngest','cousin'} <= ids)

    def test_no_legacy_brand_or_personal_examples(self):
        blocked = re.compile('|'.join(['Jeep' + 'ney School', 'Pepper' + 'dine University', 'cyber' + 'security', 'Los ' + 'Angeles', 'Bryan ' + 'Lachica', 'Lu' + 'cky']), re.I)
        for path in ROOT.rglob('*'):
            if path.is_file() and path.suffix.lower() in {'.html','.md','.js','.css','.json','.txt','.py','.yml','.yaml'}:
                self.assertIsNone(blocked.search(path.read_text(encoding='utf-8', errors='ignore')), str(path))

    def test_no_external_runtime_dependencies(self):
        html = (ROOT / 'index.html').read_text(encoding='utf-8')
        css = (ROOT / 'assets/css/styles.css').read_text(encoding='utf-8')
        self.assertIsNone(re.search(r'<(?:script|link)[^>]+https?://', html, re.I))
        self.assertIsNone(re.search(r'url\(\s*["\']?https?://', css, re.I))

    def test_manifest_hashes(self):
        manifest = ROOT / 'MANIFEST.sha256'
        if not manifest.exists():
            self.skipTest('Manifest is generated by validation')
        for line in manifest.read_text(encoding='utf-8').splitlines():
            digest, relative = line.split('  ', 1)
            self.assertEqual(hashlib.sha256((ROOT / relative).read_bytes()).hexdigest(), digest)

    def test_cli_validate(self):
        result = subprocess.run([sys.executable, str(ROOT / 'tagalog.py'), 'validate'], capture_output=True, text=True)
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn('PASS:', result.stdout)

    def test_cli_preview(self):
        result = subprocess.run([sys.executable, str(ROOT / 'tagalog.py'), 'study', '--count', '3', '--seed', '7', '--preview'], capture_output=True, text=True)
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(len([line for line in result.stdout.splitlines() if line.strip()]), 3)


if __name__ == '__main__':
    unittest.main()
